### PR TITLE
Fix wrong dependency scopes

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by ljacqu** [comment]
One question about this - why are there exclusions to `provided` scope? Provided is available at compile time + in testing and then expected to be supplied externally.

Unit tests are now failing because of the exclusions from Reflections - could reflections not just be put to scope `provided` too?

**Comment by sgdc3** [comment]
we need first to split it into nodules

**Comment by sgdc3** [comment]
injector-core
injector-testing
injector-reflections

**Comment by ljacqu** [comment]
I've given you push access to the main repo. Could we keep the test runner in the core module though? All of its specific dependencies (JUnit, Mockito) are not included in the JAR and shouldn't: if some project doesn't use JUnit and Mockito, they will have no use for the runner.

**Comment by sgdc3** [comment]
I was trying to reduce the size of the non shaded file, at least to 30kb

**Pull request closed without merging**
